### ISSUE TITLE
error when using pykml with python 3

### ISSUE THREAD

**Issue by fredlllll** [shabble/pykml#3]
just tried using pykml in a  python 3 project and got this error when importing it

```
File "/usr/local/lib/python3.5/dist-packages/pykml/factory.py", line 216
    print write_python_script_for_kml_document(doc)
                                            ^ SyntaxError: invalid syntax
```

the ^ that points to the syntax error is probably wrong cause i had to copy this from an escaped string, and some indentation got lost

i couldnt find anything about that issue, so lets hope im not just being stupid (pycharm also complains about that part in the code)

**Comment by fredlllll** [comment]
i just noticed this is a fork... my bad

**Comment by fredlllll** [comment]
wait... is this the official one or not?

**Comment by shabble** [comment]
> wait... is this the official one or not?

No. I put it here from a conversion from (IIRC) mercurial project on code.google.com back when it was alive, and fixed a few bugs. I haven't touched it for some years, so py3k support is deeply unlikely unless someone volunteers :-)

Your error appears to be with py3 requiring `print(...)` as a function rather than the `print ...` it has there. I daresay there will be other places that need fixing too though

**Comment by fredlllll** [comment]
yeah i guessed that its the missing ()

well, i just have to write an xml string to a kml file. will go with formatting a string then. yay deadlines
